### ISSUE TITLE
Discrepancy between (From)BlochSphere documentation and implementation

### ISSUE THREAD

**Issue by alastair-abbott** [rogercolbeck/QI#1]
According to the documentation, these functions should return/be passed a vector of the form {r1,r2,r3}, but in the implementation they use a vector of the form {{x},{y},{z}}. Unlike for kets, where there is a clear reason to use the column vector form, I don't see a reason not to use a standard list for this, as in the documentation.

**Comment by rogercolbeck** [comment]
Thanks -- resolved.
